const test = require('node:test');
const assert = require('node:assert/strict');
const express = require('express');
const session = require('express-session');
const { createMobileSessionRouter } = require('../src/mobileSession');

test('native session authenticates, rotates cookies, refreshes roles, revokes inactive users and logs out', async t => {
  const user = { id: 7, username: 'tester', full_name: 'Test User', role: 'member', status: 'online', active: 1, password_hash: 'never-exposed' };
  const db = { prepare: sql => ({ get: async value => sql.includes('username =') ? (value === user.username && user.active ? { ...user } : undefined) : (value === user.id ? { ...user } : undefined) }) };
  const app = express();
  app.use(express.json());
  app.use(session({ secret: 'test-session-secret', resave: false, saveUninitialized: false }));
  app.use('/api/mobile', createMobileSessionRouter({ db, compare: async value => value === 'correct' }));
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => new Promise(resolve => server.close(resolve)));
  const base = `http://127.0.0.1:${server.address().port}/api/mobile`;
  let cookie;
  const request = (path, body) => fetch(base + path, { method: body ? 'POST' : 'GET', headers: { 'Content-Type': 'application/json', ...(cookie ? { Cookie: cookie } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
  assert.equal((await request('/session')).status, 401);
  assert.equal((await request('/login', { username: [], password: 'correct' })).status, 400);
  assert.equal((await request('/login', { username: 'tester', password: 'wrong' })).status, 401);
  const first = await request('/login', { username: 'tester', password: 'correct' });
  assert.equal(first.status, 200);
  assert.equal(first.headers.get('cache-control'), 'no-store');
  assert.equal((await first.json()).user.password_hash, undefined);
  cookie = first.headers.get('set-cookie').split(';')[0];
  const second = await request('/login', { username: 'tester', password: 'correct' });
  const oldCookie = cookie;
  cookie = second.headers.get('set-cookie').split(';')[0];
  assert.notEqual(cookie, oldCookie);
  assert.equal((await fetch(base + '/session', { headers: { Cookie: oldCookie } })).status, 401);
  user.role = 'admin';
  assert.equal((await (await request('/session')).json()).user.role, 'admin');
  user.active = 0;
  assert.equal((await request('/session')).status, 401);
  user.active = 1;
  const third = await request('/login', { username: 'tester', password: 'correct' });
  cookie = third.headers.get('set-cookie').split(';')[0];
  assert.equal((await request('/logout', {})).status, 200);
  assert.equal((await request('/session')).status, 401);
});
